version: 2
updates:
  - package-ecosystem: npm
    directory: "/" # Root directory
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        # Ignore all dependencies inside testapp folders
        paths:
          - "testapp-**/**"