# Uncomment, if you want to build the app with the old architecture
# ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# New thingies since 0.80 - downloads precompiled RN Core & RN dependencies instead of building from source
ENV['RCT_USE_RN_DEP'] = '1'
ENV['RCT_USE_PREBUILT_RNCORE'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'testapp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Wultra specific
    fix_dev_team(installer, 'KTT9G859MR')

    # Suppress deprecated-declarations warnings from PowerAuth pods.
    # PowerAuth2 1.9.5 uses kSecUseAuthenticationUIFail which was deprecated
    # in iOS 14. In newer Xcode/SDK versions this may be treated as a build error.
    installer.pods_project.targets.each do |target|
      next unless target.name.start_with?('PowerAuth')
      target.build_configurations.each do |config|
        flags = config.build_settings['OTHER_CFLAGS']
        if flags.is_a?(Array)
          config.build_settings['OTHER_CFLAGS'] = flags + ['-Wno-deprecated-declarations']
        else
          config.build_settings['OTHER_CFLAGS'] = "#{flags || '$(inherited)'} -Wno-deprecated-declarations"
        end
      end
    end
  end
end

# Wultra specific. Fix dev team for all configurations and targets
def fix_dev_team(installer, team_id)
  # https://github.com/CocoaPods/CocoaPods/issues/8891
  def fix_config_dev_team(config, team_id)
    if config.build_settings['DEVELOPMENT_TEAM'].nil?
      config.build_settings['DEVELOPMENT_TEAM'] = team_id
    end
  end
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
      fix_config_dev_team(config, team_id)
    end
    project.targets.each do |target|
      target.build_configurations.each do |config|
        fix_config_dev_team(config, team_id)
      end
    end
  end
end
