const path = require('path');
const powerAuthRoot = path.join(__dirname, '..', 'packages', 'lib-rn', 'build', 'rn');

module.exports = {
  project: {
    ios: {
      automaticPodsInstallation: true,
    },
  },
  dependencies: {
    'react-native-powerauth-mobile-sdk': {
      root: powerAuthRoot,
      platforms: {
        // Keep both native locations explicit. The package root is generated by
        // prepare:powerauth, so relying on CLI discovery can make the Gradle
        // settings and app plugins see different dependency models.
        ios: {
          podspecPath: path.join(powerAuthRoot, 'react-native-powerauth-mobile-sdk.podspec'),
        },
        android: {
          sourceDir: path.join(powerAuthRoot, 'android'),
        },
      },
    },
  },
};
