name: Build

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:

jobs:
  build-ios:
    name: Build React Native Test App - iOS
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/actions/prepare
      - name: Build RN iOS
        run: npm run buildReactIos
  build-android:
    name: Build React Native Test App - Android
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/actions/prepare
      - name: Build RN Android
        run: npm run buildReactAndroid