name: Build Cordova Integration

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:

jobs:
  build-ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/actions/prepare
        with:
          env-file: ${{ secrets.ENV_TEST_FILE }}
      - name: Build Cordova iOS
        run: yarn buildCordovaIos
  build-android:
    name: Android
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/actions/prepare
        with:
          env-file: ${{ secrets.ENV_TEST_FILE }}
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build Cordova Android
        run: yarn buildCordovaAndroid