name: Build Library

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:

jobs:
  build-library:
    name: Build and Pack
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/actions/prepare
        with:
          env-file: ${{ secrets.ENV_TEST_FILE }}
      - name: Library build
        run: npm run build