name: iOS Tests

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:

jobs:
  test-cordova:
    name: Test Cordova iOS
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm i
      - name: Install Cordova
        run: npm install -g cordova
      - name: Set .env file
        env:
          ENV_TEST_FILE: ${{ secrets.ENV_TEST_FILE }}
        run: echo "$ENV_TEST_FILE" > testapp/.env
      - name: Run iOS Tests
        run: npm run buildAndRunCordovaIosTests